### ISSUE TITLE
`URL` is undefined

### ISSUE THREAD

**Issue by jocull** [devongovett/blob-stream#3]
This line dos not appear to work in Node v6 (have not tested other versions)

```
var URL = global.URL || global.webkitURL || global.mozURL;
```

**Comment by devongovett** [comment]
This module is for use in the browser, not node.

**Comment by jocull** [comment]
My apologies. I had initially mixed up some of the PDFKit examples as they vary whether you are using Node or a browser.

Thanks for the reply!
